Updated styling
bpytlik/sps-summer2022-team-10 pull request #6
Opened 2022-07-09 23:53 UTC by akyukii

2022-07-09 23:57 UTC, closed without merging

2022-07-09 23:57 UTC, akyukii commented
I forgot to pull from Tianyu's the first time

2022-07-09 23:57 UTC, IreneC2020 commented on src/main/webapp/index.html
> +                <input name="text-input" placeholder="Enter Item" style="border-radius: 15px; width: 300px; height: 20px; border-color:#0A6644; padding: 5px; padding-left: 15px; font-family: 'DM Sans
we need id="item-name" in order for the addToCart() to fetch data

2022-07-09 23:59 UTC, IreneC2020 commented on src/main/webapp/index.html
> +            <form action="/form-handler" method="POST">
we are not using form-handler any more and the method=post now is in addToCart() in script.js

2022-07-10 00:02 UTC, IreneC2020 requested changes
please review the comment and make the update so index.html will be able to interact with script.js and return result. 
And I am not seeing the shopping list item will show up after user click submit, will there be other PR on this?
Thanks!